version: '3'
services:
  chatgpt-slack-bot:
    build :
      context : .
      dockerfile : Dockerfile
      args :
        PROXY: ${PROXY}
    command:
      - devbox
      - run
      - start
    volumes:
      - ./:/code